{% set name = "aiohttp" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 176f1d2b2bc07044f4ed583216578a72a2bd35dffdeb92e0517d0aaa29d29549

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - async-timeout <4.0,>=3.0
    - attrs >=17.3.0
    - chardet >=2.0,<4.0
    - idna_ssl >=1.0  # [py<37]
    - multidict >=4.5,<5.0
    - typing-extensions >=3.6.5  # [py<37]
    - yarl >=1.0,<1.6.0

test:
  imports:
    - aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
