bot:
  run_deps_from_wheel: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
linux_aarch64:
  enabled: true
linux_ppc64le:
  enabled: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
test_on_native_only: true
conda_build:
  pkg_format: '2'
